# Generated by Django 3.0.4 on 2020-04-06 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='主键')),
                ('text', models.TextField(help_text='待办事项详情', verbose_name='待办事项详情')),
                ('status', models.BooleanField(help_text='完成状态', verbose_name='完成状态')),
                ('user_id', models.ForeignKey(help_text='所属用户id', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '待办事项信息',
                'verbose_name_plural': '待办事项信息',
                'db_table': 'tb_backlog',
            },
        ),
    ]
