# Generated by Django 3.0.4 on 2020-04-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlogmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
