# Generated by Django 3.0.4 on 2020-04-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('debugtalks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DebugTalks',
            new_name='DebugTalksModel',
        ),
    ]
